### ISSUE TITLE
Doesn't work in Catalina 10.15.1

### ISSUE THREAD

**Issue by richardtop** [Ji4n1ng/OpenInTerminal#65]
## What is the issue?
The plugin doesn't work on the latest macOS Catalina 10.15.1

## How does one reproduce the issue?
Install the plugin via Homebrew
Press "open in terminal" in any of the finder windows.

## Screenshots
![image](https://user-images.githubusercontent.com/8013017/68298756-d6ff9f00-00a2-11ea-9096-7ec5e711e09b.png)
![image](https://user-images.githubusercontent.com/8013017/68298766-e0890700-00a2-11ea-871a-a2472d96cdc7.png)

## Debug information (Logs, OS, Hardware, Version, etc.)
macOS Catalina 10.15.1, tested on both Mac Mini & MacBook Pro

**Comment by richardtop** [comment]
Fixed by finding "open in terminal" in spotlight & launching the app

**Comment by aceslick911** [comment]
I am having this issue, i've opened the app and it still does not launch

**Comment by aceslick911** [comment]
![image](https://user-images.githubusercontent.com/1932043/72115596-bc47f000-339b-11ea-81d6-a8e8b826c6e8.png)

Catalina beta

**Comment by richardtop** [comment]
@aceslick911  could you try my solution from the comment above?

**Comment by aceslick911** [comment]
tried opening it via terminal and ensuring the option was enabled in preferences. Clicking on any of the actions does nothing. Is there some kind of logs i can provide to help solve this?

**Comment by richardtop** [comment]
No idea, for me the app works perfectly so far. Could you try reinstalling it? Or open security settings and see if there is an "Open Anyway" button.
